# Generated by Django 4.1.4 on 2023-02-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65)),
                ('num_alumn', models.IntegerField()),
                ('anio_lec', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
