# Generated by Django 4.1.4 on 2023-02-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65)),
                ('apellido', models.CharField(max_length=65)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.materia')),
            ],
        ),
    ]
