# Generated by Django 4.1.4 on 2023-03-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('paralelo', models.IntegerField()),
                ('grado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.CharField(max_length=65, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65)),
                ('apellido', models.CharField(max_length=65)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=80)),
                ('curso', models.IntegerField()),
                ('materia', models.ManyToManyField(blank=True, to='school.materia')),
            ],
        ),
    ]
